#!/usr/bin/env bash
set -euo pipefail

DOMAIN_NAME=$1
APP_PORT=$2
RANDOM_AUTH_KEY=$(openssl rand -base64 32 | tr -d /=+ | cut -c1-32)

# Nginx Config
sed "s/{{DOMAIN_NAME}}/${DOMAIN_NAME}/g; s/{{APP_PORT}}/${APP_PORT}/g" /etc/nginx/sites-available/nuxtapp.conf.template > /etc/nginx/sites-available/${DOMAIN_NAME}.conf
ln -s /etc/nginx/sites-available/${DOMAIN_NAME}.conf /etc/nginx/sites-enabled/${DOMAIN_NAME}.conf

# Supervisor Config
sed "s/{{DOMAIN_NAME}}/${DOMAIN_NAME}/g; s/{{APP_PORT}}/${APP_PORT}/g; s/{{RANDOM_AUTH_KEY}}/${RANDOM_AUTH_KEY}/g" /etc/supervisor/conf.d/nuxtapp.conf.template > /etc/supervisor/conf.d/${DOMAIN_NAME}.conf

# Clone Repo and setup
mkdir /var/www/websites/${DOMAIN_NAME}
cd /var/www/websites/${DOMAIN_NAME}
git clone git@github.com:mktcode/${DOMAIN_NAME}.git .

### Check for better way (use nuxtapp user to clone/pull)
git config --global --add safe.directory /var/www/websites/${DOMAIN_NAME}
###

npm ci
npm run build
chown -R websites:websites /var/www/websites/${DOMAIN_NAME}

# Reload Services
nginx -t
systemctl reload nginx
supervisorctl reread
supervisorctl update