#!/usr/bin/env bash
set -euo pipefail

DOMAIN_NAME=$1
EMAIL=$2

DOMAINS=(-d "${DOMAIN_NAME}" -d "www.${DOMAIN_NAME}")
certbot --nginx "${DOMAINS[@]}" -m "${EMAIL}" --agree-tos --non-interactive --redirect